/*
CREATE DATABASE '/home/firebird/timetrack.fb' PAGE_SIZE 32768;
*/
CREATE DOMAIN GUID AS VARCHAR(36);
CREATE DOMAIN NAME AS VARCHAR(30);
CREATE DOMAIN BOOL AS CHAR(1) DEFAULT '0' CHECK (VALUE IN ('0','1'));
CREATE DOMAIN MEMO AS BLOB SUB_TYPE 1;

CREATE TABLE PERSON (
  PE_ID GUID NOT NULL,
  PE_FIRSTNAME NAME NOT NULL,
  PE_LASTNAME NAME NOT NULL,
  CONSTRAINT PK_PERSON PRIMARY KEY (PE_ID)
);

CREATE TABLE PROJECT (
  PJ_ID GUID NOT NULL,
  PJ_NAME NAME NOT NULL,
  CONSTRAINT PK_PROJECT PRIMARY KEY (PJ_ID)
);

CREATE TABLE INTERRUPT (
  IR_ID GUID NOT NULL,
  IR_PERSON_FK GUID NOT NULL,
  IR_TIMESTAMP TIMESTAMP DEFAULT 'NOW' NOT NULL,
  IR_DURATION TIME,
  CONSTRAINT PK_INTERRUPT PRIMARY KEY (IR_ID),
  CONSTRAINT R_INTERRUPT_PERSON FOREIGN KEY (IR_PERSON_FK) REFERENCES PERSON (PE_ID)
);

CREATE INDEX I_INTERRUPT_TIMESTAMP ON INTERRUPT (IR_TIMESTAMP);

CREATE TABLE TODO (
  TO_ID GUID NOT NULL,
  TO_PROJECT_FK GUID,
  TO_CREATEDON TIMESTAMP DEFAULT 'NOW',
  TO_DONE BOOL NOT NULL,
  TO_TITLE VARCHAR(150) NOT NULL,
  TO_REMARK MEMO,
  CONSTRAINT PK_TODO PRIMARY KEY (TO_ID)
);

CREATE INDEX I_TODO_PROJECT ON TODO (TO_PROJECT_FK);
CREATE INDEX I_TODO_CREATEDON ON TODO (TO_CREATEDON);

CREATE TABLE TASK (
  TA_ID GUID NOT NULL,
  TA_PROJECT_FK GUID NOT NULL,
  TA_CREATEDON TIMESTAMP DEFAULT 'NOW',
  TA_STATUS INT DEFAULT 0 NOT NULL,
  TA_TITLE VARCHAR(150) NOT NULL,
  TA_DESCRIPTION MEMO,
  TA_BUGID INT,
  CONSTRAINT PK_TASK PRIMARY KEY (TA_ID)
);

CREATE INDEX I_TASK_PROJECT ON TASK (TA_PROJECT_FK);
CREATE INDEX I_TASK_CREATEDON ON TASK (TA_CREATEDON);

CREATE TABLE TIMETRACK (
  TT_ID GUID NOT NULL,
  TT_TASK_FK GUID NOT NULL,
  TT_START TIMESTAMP DEFAULT 'NOW' NOT NULL,
  TT_STOP TIMESTAMP,
  CONSTRAINT PK_TIMETRACK PRIMARY KEY (TT_ID),
  CONSTRAINT R_TIMETRACK_TASK FOREIGN KEY (TT_TASK_FK) REFERENCES TASK (TA_ID)
);

